Codebase/events/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import CustomPasswordResetCompleteView

urlpatterns = [
    # Path Convertors
    # int: numbers
    # str: strings
    # path: whole URLS
    # slug: hyphen-and_underscore stuff
    # UUID: universually unique identifier

    path('', views.home, name="home"), # point to home function in views.py
    path('events/', views.events, name='events'),    
    path('about', views.about, name="about"),
    path('account', views.account, name="account"),
    path('groups', views.groups, name="groups"),
    path('signin/',views.signin, name='signin'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('signout/',views.signout, name='signout'),
    path('signup/',views.signup, name='signup'),
    path('venues/', views.venues, name='venues'),
    path('vendors/', views.vendors, name='vendors'),
    path('guests', views.guests, name='guests'),

    path('add_venues', views.add_venues, name='add_venues'),
    path('add_guests', views.add_guests, name='add_guests'),
    path('add_vendors', views.add_vendors, name='add_vendors'),
    path('add_groups', views.add_groups, name='add_groups'),
    path('join_group/<int:group_id>/', views.join_group, name='join_group'),
    path('leave_group/<int:group_id>/', views.leave_group, name='leave_group'),
    path('add_events/', views.add_events, name='add_events'),
    path('attended_events/', views.attended_events, name='attended_events'),
    path('attend_event/<int:event_id>/', views.attend_event, name='attend_event'),
    path('clear_attended_events/', views.clear_attended_events, name='clear_attended_events'),
    path('saved_events/', views.saved_events, name='saved_events'),
    path('save_event/<int:event_id>/', views.save_event, name='save_event'),
    path('clear_saved_events/', views.clear_saved_events, name='clear_saved_events'),
    ]

Codebase/events/models.py
from django.db import models
import base64


class Affiliated(models.Model):
    group_id = models.IntegerField(db_column='Group_ID', primary_key=True)  # Field name made lowercase. The composite primary key (Group_ID, Event_ID) found, that is not supported. The first column is selected.
    event = models.ForeignKey('Events', models.DO_NOTHING, db_column='Event_ID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Affiliated'
        unique_together = (('group_id', 'event'),)


class ArrangesVendor(models.Model):
    v_name = models.OneToOneField('Vendors', models.DO_NOTHING, db_column='V_name', primary_key=True)  # Field name made lowercase. The composite primary key (V_name, Org_username) found, that is not supported. The first column is selected.
    org_username = models.ForeignKey('User', models.DO_NOTHING, db_column='Org_username')  # Field name made lowercase.
    booth_no = models.IntegerField(db_column='Booth_no')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Arranges_Vendor'
        unique_together = (('v_name', 'org_username'),)


class Attends(models.Model):
    u_username = models.CharField(db_column='U_username', primary_key=True, max_length=255)  # Field name made lowercase. The composite primary key (U_username, Event_ID) found, that is not supported. The first column is selected.
    event = models.ForeignKey('Events', models.DO_NOTHING, db_column='Event_ID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Attends'
        unique_together = (('u_username', 'event'),)


class Saved(models.Model):
    u_username = models.CharField(db_column='U_username', primary_key=True, max_length=255)  # Field name made lowercase. The composite primary key (U_username, Event_ID) found, that is not supported. The first column is selected.
    event = models.ForeignKey('Events', models.DO_NOTHING, db_column='Event_ID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Saved'
        unique_together = (('u_username', 'event'),)


class Dates(models.Model):
    date_code = models.DateField(db_column='Date_Code', primary_key=True)  # Field name made lowercase.
    no_of_events = models.CharField(db_column='No_of_Events', max_length=255, blank=True, null=True)  # Field name made lowercase.
    events_occuring = models.CharField(db_column='Events_Occuring', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Dates'


class Events(models.Model):
    event_id = models.IntegerField(db_column='Event_ID', primary_key=True)  # Field name made lowercase.
    e_name = models.CharField(db_column='E_name', max_length=255)  # Field name made lowercase.
    org_username = models.ForeignKey('User', models.DO_NOTHING, db_column='Org_username')  # Field name made lowercase.
    venue_add = models.ForeignKey('LocationsVenue', models.DO_NOTHING, db_column='Venue_add')  # Field name made lowercase.
    e_site = models.CharField(db_column='E_site', max_length=255)  # Field name made lowercase.
    e_desc = models.CharField(db_column='E_desc', max_length=255)  # Field name made lowercase.
    e_date = models.DateTimeField(db_column='E_date')  # Field name made lowercase.
    e_category = models.CharField(db_column='E_category', max_length=255)  # Field name made lowercase.
    e_img = models.ImageField(upload_to='e_img/', null=True, blank=True, db_column='Event_img')

    def get_image(self):
        if self.e_img:
            return base64.b64encode(self.e_img).decode('utf-8')
        return None
    
    class Meta:
        managed = False
        db_table = 'Events'


class Guest(models.Model):
    guest_id = models.AutoField(db_column='Guest_ID', primary_key=True)  # Auto-incrementing primary key
    g_type = models.CharField(db_column='G_Type', max_length=255)
    g_name = models.CharField(db_column='G_name', max_length=255)
    g_info = models.TextField(db_column='G_info')

    class Meta:
        managed = False
        db_table = 'Guest'

    def __str__(self):
        return self.g_name


class HasGuests(models.Model):
    guest = models.ForeignKey(Guest, models.DO_NOTHING, db_column='Guest_ID', primary_key=True)  # Field name made lowercase. The composite primary key (Guest_ID, Event_ID) found, that is not supported. The first column is selected.
    event = models.ForeignKey(Events, models.DO_NOTHING, db_column='Event_ID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Has_Guests'
        unique_together = (('guest', 'event'),)


class HasVendors(models.Model):
    v_name = models.ForeignKey('Vendors', models.DO_NOTHING, db_column='V_name', primary_key=True)  # Field name made lowercase. The composite primary key (V_name, Event_ID) found, that is not supported. The first column is selected.
    event = models.ForeignKey(Events, models.DO_NOTHING, db_column='Event_ID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Has_Vendors'
        unique_together = (('v_name', 'event'),)


class IsAt(models.Model):
    l_address = models.ForeignKey('LocationsVenue', models.DO_NOTHING, db_column='L_Address', primary_key=True)  # Field name made lowercase. The composite primary key (L_Address, Event_ID) found, that is not supported. The first column is selected.
    event = models.ForeignKey(Events, models.DO_NOTHING, db_column='Event_ID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Is_at'
        unique_together = (('l_address', 'event'),)


class IsOn(models.Model):
    date_code = models.OneToOneField(Dates, models.DO_NOTHING, db_column='Date_Code', primary_key=True)  # Field name made lowercase. The composite primary key (Date_Code, Event_ID) found, that is not supported. The first column is selected.
    event = models.ForeignKey(Events, models.DO_NOTHING, db_column='Event_ID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Is_on'
        unique_together = (('date_code', 'event'),)


class LocationsVenue(models.Model):
    address = models.CharField(db_column='Address', primary_key=True, max_length=255)  # Field name made lowercase.
    l_owner = models.ForeignKey('User', models.DO_NOTHING, db_column='L_Owner')  # Field name made lowercase.
    l_name = models.CharField(db_column='L_Name', max_length=255)  # Field name made lowercase.
    city = models.CharField(db_column='City', max_length=255)  # Field name made lowercase.
    province_state = models.CharField(db_column='Province_state', max_length=255)  # Field name made lowercase.
    country = models.CharField(db_column='Country', max_length=255)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Locations_Venue'

    def __str__(self):
        return self.address


class PartOf(models.Model):
    group = models.ForeignKey('UserGroups', models.DO_NOTHING, db_column='Group_ID', primary_key=True)  # Field name made lowercase. The composite primary key (Group_ID, Username) found, that is not supported. The first column is selected.
    username = models.ForeignKey('User', models.DO_NOTHING, db_column='Username')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Part_of'
        unique_together = (('group', 'username'),)


class Profile(models.Model):
    u_username = models.ForeignKey('User', models.DO_NOTHING, db_column='U_Username', db_comment='Username [->User] (req)')  # Field name made lowercase.
    attended_events = models.CharField(db_column='Attended_Events', max_length=255, blank=True, null=True, db_comment='Attended Events (opt)')  # Field name made lowercase.
    saved_events = models.CharField(db_column='Saved_Events', max_length=255, blank=True, null=True, db_comment='Saved Events (opt)')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Profile'


class User(models.Model):
    username = models.CharField(db_column='Username', primary_key=True, max_length=255, db_comment='Username (req)')  # Field name made lowercase.
    f_name = models.CharField(db_column='F.name', max_length=255, db_comment='First Name (req)')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    m_name = models.CharField(db_column='M.Name', max_length=255, blank=True, null=True, db_comment='Middle Name (opt)')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    l_name = models.CharField(db_column='L.Name', max_length=255, db_comment='Last Name (req)')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    email = models.CharField(db_column='Email', max_length=255, db_comment='Email (req)')  # Field name made lowercase.
    birthday = models.DateField(db_column='Birthday', db_comment='Birthday (req)')  # Field name made lowercase.
    ord_flag = models.IntegerField(db_column='Ord_flag', blank=True, null=True, db_comment='Ord Flag? (opt)')  # Field name made lowercase.
    org_id = models.IntegerField(db_column='Org_ID', blank=True, null=True, db_comment='Org ID (opt)')  # Field name made lowercase.

    USERNAME_FIELD = 'email'

    def set_password(self, force_pass):
        pass

    class Meta:
        managed = False
        db_table = 'User'


class UserGroups(models.Model):
    group_id = models.AutoField(db_column='Group_ID', primary_key=True)  # Field name made lowercase.
    ug_name = models.CharField(db_column='UG_Name', max_length=255)  # Field name made lowercase.
    g_desc = models.CharField(db_column='g_desc', max_length=255)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'User_Groups'


class Vendors(models.Model):

Codebase/events/templates/events/about.html
{% extends 'events/base.html' %}

{% block content %}

    <center class="HH">
        
        <div class="content">
            <h2>About HappenHarbor</h2>
            <h4>HappenHarbor is a UCalgary CPSC 471 Project Created By:<br/>
                <br/>
                [CPSC 471 F23 Group 38]<br/>
                Jason Ngu (UCID 30145770)<br/>
                Brian Tran (UCID 30064686)<br/>
                Carter Tam (UCID 30146065)<br/>
                <br/>
                Using a MySQL Database and Django Back-end.<br/>
                
                <br/>
                List of Libraries and Resources Used for the Project:<br/><br/>
                MySQL 8.2.0<br/>
                Django 4.2<br/>
                Bootstrap v5.3<br/>
                React 18<br/>
                Python 3.12<br/>
                Pillow 10.1.0
                HTML/CSS/JavaScript<br/>
                <br/>
                The HappenHarbor Logo was created using:<br>
                LOGO.com<br/><br/>
                The Website Background was AI generated using:<br/>
                stablediffusionweb.com<br/>
            </h4>
        </div>
    </center>

{% endblock %}

Codebase/events/templates/events/add_events.html
{% extends 'events/base.html' %}

<style>
    .scrollable-checkboxes {
        max-height: 80px;
        overflow-y: auto;
        border: 1px solid #ddd;
        padding: 10px;
        margin-bottom: 10px;
    }
</style>

{% block content %}
    <center class="HH2">
        <div class="center-container">
            <h2>Add Event</h2><br/>
        </div>

        <div class="center-container">
            <form method="post" action="{% url 'add_events' %}" enctype="multipart/form-data">
                {% csrf_token %}
                
                <div class="form-group">
                    <label for="{{ form.e_name.id_for_label }}">Event Name:</label>
                    {{ form.e_name }}
                </div>

                <div class="form-group">
                    <label for="{{ form.venue_add.id_for_label }}">Venue:</label>
                    {{ form.venue_add }}
                </div>

                <div class="form-group">
                    <label for="{{ form.e_site.id_for_label }}">Event Site:</label>
                    {{ form.e_site }}
                </div>

                <div class="form-group">
                    <label for="{{ form.e_desc.id_for_label }}">Event Description:</label>
                    {{ form.e_desc }}
                </div>

                <div class="form-group">
                    <label for="{{ form.e_date.id_for_label }}">Event Date:</label>
                    {{ form.e_date }}
                </div>

                <div class="form-group">
                    <label for="{{ form.e_category.id_for_label }}">Event Category:</label>
                    {{ form.e_category }}
                </div>

                <div class="form-group">
                    <label for="{{ form.e_img.id_for_label }}">Event Image:</label>
                    {{ form.e_img }}
                </div>

                <div class="border-box-3">
                    Select Guests:
                    <div style="overflow-y: scroll; max-height: 150px;">
                        {{ form.guests }}
                    </div>
                </div>

                <button class="btn-lg btn-primary" type="submit">Add Event</button>
            </form>
        </div>
    </center>
{% endblock %}

Codebase/events/templates/events/add_guests.html
{% extends 'events/base.html' %}

{% block content %}
  {% if user.is_authenticated %}
    <center class="HH2">
      <div class="center-container">
        <h2>Add Guest</h2><br/>
      </div>

      <div class="center-container">
        <form method="post" action="{% url 'add_guests' %}">
          {% csrf_token %}
        
          <div class="form-group">
            <label for="{{ form.g_type.id_for_label }}">Guest Type:</label>
            <input type="text" name="{{ form.g_type.name }}" id="{{ form.g_type.id_for_label }}" class="form-control" required>
          </div>
        
          <div class="form-group">
            <label for="{{ form.g_name.id_for_label }}">Guest Name:</label>
            <input type="text" name="{{ form.g_name.name }}" id="{{ form.g_name.id_for_label }}" class="form-control" required>
          </div>
        
          <div class="form-group">
            <label for="{{ form.g_info.id_for_label }}">Description:</label>
            <textarea name="{{ form.g_info.name }}" id="{{ form.g_info.id_for_label }}" class="form-control" required></textarea>
          </div>
        
          <br/>
        
          <button type="submit" class="btn-lg btn-success">Add Guest</button>
        </form>
        
      </div>
  {% else %}
    <div class="center-container">
      <h2>Please log in to add guests.</h2>
    </div>
  {% endif %}
</center>
{% endblock %}

Codebase/events/templates/events/add_vendors.html
{% extends 'events/base.html' %}

{% block content %}
  {% if user.is_authenticated %}
    <center class="HH2">
      <div class="center-container">
        <h2>Add Vendor</h2><br/>
      </div>

      <div class="center-container">
        <form method="post" action="{% url 'add_vendors' %}">
          {% csrf_token %}

          <div class="form-group">
            <label for="{{ form.c_name.id_for_label }}">Vendor Name:</label>
            <input type="text" name="{{ form.c_name.name }}" id="{{ form.c_name.id_for_label }}" class="form-control" required>
          </div>

          <div class="form-group">
            <label for="{{ form.types_of_product.id_for_label }}">Types of Product:</label>
            <input type="text" name="{{ form.types_of_product.name }}" id="{{ form.types_of_product.id_for_label }}" class="form-control" required>
          </div>

          <div class="form-group">
            <label for="{{ form.v_address.id_for_label }}">Address:</label>
            <input type="text" name="{{ form.v_address.name }}" id="{{ form.v_address.id_for_label }}" class="form-control" required>
          </div>

          <input type="hidden" name="{{ form.c_owner.name }}" id="{{ form.c_owner.id_for_label }}" value="{{ user.first_name }} {{ user.username }} {{ user.last_name }}">
          <br/>

          <button type="submit" class="btn-lg btn-success">Add Vendor</button>
        </form>
      </div>
    </center>
  {% else %}
    <div class="center-container">
      <h2>Please log in to add vendors.</h2>
    </div>
  {% endif %}
{% endblock %}

Codebase/events/templates/events/add_venue.html
<!-- add_venue.html -->
{% extends 'events/base.html' %}
<!DOCTYPE html>

{% block content %}

    <center class="HH2">
        <style>
            body {
                background-image: url('../../static/HF169.png');
                background-attachment: fixed;
                background-size: cover; /* Optional: Adjust the background size as needed */
            }

            .center-container {
                display: flex;
                justify-content: center;
                align-items: center;
            }
        </style>

        <h2>Add Venue</h2><br/>
    </center>

    <div class="center-container">
        <form method="post" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn-lg btn-primary" type="submit">Add Venue</button>
        </form>
    </div>

{% endblock %}

Codebase/events/templates/events/attend_event.html
{% extends 'events/base.html' %}

{% block content %}
    <center class="HH2">
        <div class="container">
            <h2>Event Attended!</h2>
            <p>You have successfully attended the event.</p>
            <a href="{% url 'events' %}" class="btn btn-primary">Back to Events</a>
        </div>
    </center>

{% endblock %}

Codebase/events/templates/events/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" type="image/ico" href="{% static 'favicon.ico' %}" >

    <title>HappenHarbor</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/background.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/centered.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    
  </head>
  
  <body>
        {% include 'events/navbar.html' %}
        <br/>
        <div class="container">
          {% block content %}
          {% endblock %}
        </div>
        
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

Codebase/events/templates/events/events.html
{% extends 'events/base.html' %}

{% block content %}
    <center class="HH2">
        <div class="center-container">
            <h2>Find Events</h2><br/>
        </div>
    </center>

    <div class="center-container">
        <a href="{% url 'add_events' %}" class="btn-lg btn-primary mx-1">Add Event</a>
        <form method="get" action="{% url 'events' %}">
            <input class="dd_text" type="text" name="q" placeholder="Search...">
            <select class="dd_test" name="search_field">
                <option value="event_name">Event Name</option>
                <option value="venue">Venue</option>
                <option value="organizer">Organizer</option>
                <option value="category">Category</option>
                <option value="guest">Guests</option>
            </select>
            <button class="btn-lg btn-primary" type="submit">Search</button>
        </form>
    </div>
    <br/>

    {% for e in events %}
        <div class="card">
            <div class="card-header d-flex justify-content-between align-items-center mr-2">
                <div>
                    ({{ e.org_username.f_name }}) {{ e.e_name }}
                </div>
                <div class="d-flex mr-2">
                    <form method="post" action="{% url 'attend_event' event_id=e.event_id %}" class="mr-5">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">Attend Event</button>
                    </form>
                    <form method="post" action="{% url 'save_event' event_id=e.event_id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary ml-5">Save Event</button>
                    </form>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-8">
                        <h6 class="card-title"><b>Venue: </b> {{e.venue_add.l_name}} </h6>
                        <h6 class="card-title2">{{e.venue_add.address}}, {{e.venue_add.city}}, {{e.venue_add.province_state}} </h6>
                        <p class="card-text">
                            {% if e.hasguests_set.exists %}
                                <strong>Guests:</strong>
                                {% for has_guests in e.hasguests_set.all %}
                                    {{ has_guests.guest.g_name }}{% if not forloop.last %}, {% endif %}
                                {% endfor %}<br/>
                            {% endif %}
                            {% load tz %}
                            <strong>Date:</strong> {{ e.e_date|timezone:"America/Denver"|date:"Y-m-d H:i:s" }} MST <br/>
                            <strong>Description:</strong> {{ e.e_desc }} <br/>
                            <strong>Website:</strong> <u class="link"> {{ e.e_site }} </u><br/>
                            {% if e.hasvendors_set.exists %}
                                <strong>Vendors:</strong>
                                {% for has_vendors in e.hasvendors_set.all %}
                                    {{ has_vendors.v_name.c_name }}{% if not forloop.last %}, {% endif %}
                                {% endfor %}<br/>
                            {% endif %}
                        </p>
                    </div>
                    <div class="col-md-1">
                        {% if e.e_img %}
                            <img src="data:image/png;base64,{{ e.get_image|safe }}" alt="{{ e.e_name }}" style="width: 350px; height: 200px; margin-right: 10px; border: 4px solid #468bb3; border-radius: 5px;">                        
                        {% endif %}
                    </div>  
                    <h6 class="s_events_id"> Category: "{{ e.e_category }}" | Event ID: {{ e.event_id }} </h6>
                </div>
            </div>
        </div>
        <br/>
    {% endfor %}
{% endblock %}

Codebase/events/templates/events/events_list.html
{% extends 'events/base.html' %}
<!DOCTYPE html>

{% block content %}

    <center class="HH2">
        <style>
            body {
                background-image: url('static/HF169.png');
                background-attachment: fixed;
                background-size: cover; /* Optional: Adjust the background size as needed */
            }
            
            .center-container {
                display: flex;
                justify-content: center;
                align-items: center;
            }
        </style>
        
        <h2>Find Events</h2><br/>
    </center>
  
    <!-- Make This Search Feature Actually Work -->
    <div class="center-container">
    <form method="get" action="{% url 'events_list' %}">
        <input class="dd_text" type="text" name="q" placeholder="Search...">
        <select class="dd_test" name="search_field">
            <option value="event_name">Event Name</option>
            <option value="venue">Venue</option>
            <option value="manager">Event Manager</option>
            <option value="category">Category</option>
        </select>
        <button class="btn-lg btn-primary" type="submit">Search</button>
    </form>
    </div>
  
    <br/>
  
    <!-- For Loop for All Events -->
    {% for e in events %}
      <div class="card">
          <div class="card-header">
              {{ e.e_name }}
          </div>
          <div class="card-body">
              <h6 class="card-title"><b>Venue: </b> Insert Venue Here </h6>
              <p class="card-text">
                  <ul>
                      <!-- Change back into MST time rather than UTC-->
                      <strong>Date:</strong> >Insert Date Here< <br/>              	
                      <strong>Website:</strong> <u class="link"> >Insert Website Here< </u><br/>
                      <strong>Description:</strong> >Insert Desc. Here< <br/>
                      <strong>Attendees: </strong>
                      <!-- {% for user in event.attendees.all %}
                          {{ user }},
                      {% endfor %} -->
                  </ul>
                  <h6 class="s_events_id"> Category: >Insert Category< | Event ID: {{ e.event_id }} </h6>
              </p>
          </div>
      </div>
      <br/>
  {% endfor %}
  

{% endblock %}

Codebase/events/templates/events/login-base.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>{% block title %}Django Mysql User Authentication - Login, register and Logout{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"/>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1"/>
</head>
<body>
  <div class="container">
  <header>
    <h1>Django Mysql User Authentication - Login, register and Logout</h1>
  </header>
  <hr>

  <style>
    body {
        background-image: url('static/HF169.png');
    }
  </style>

  <main>
    {% block content %}
    {% endblock %}
  </main>
  <hr>
  </div>
</body>
</html>

Codebase/events/templates/events/save_event.html
{% extends 'events/base.html' %}

{% block content %}
    <center class="HH2">
        <div class="container">
            <h2>Event Attended!</h2>
            <p>You have successfully saved the event.</p>
            <a href="{% url 'events' %}" class="btn btn-primary">Back to Events</a>
        </div>
    </center>

{% endblock %}

Codebase/events/templates/events/signin.html
<!-- The following code is adapted from: https://www.youtube.com/watch?v=6WnL0VHtPag-->

{% extends 'events/base.html' %}
  
{% block title %}Login{% endblock %}
  
{% block content %}
<div class="border-box">
  <center class="HH2">
    <h2>Sign In</h2> {{ msg }}
    <br/>
  
    <form method="post">
      {% csrf_token %}
      
      <div class="form-group">
          <label for="{{ form.username.id_for_label }}">Username:</label>
          <input type="text" name="{{ form.username.name }}" id="{{ form.username.id_for_label }}" class="form-control" style="width: 250px;" required>
      </div>

      <br/>
  
      <div class="form-group">
          <label for="{{ form.password.id_for_label }}">Password:</label>
          <input type="password" name="{{ form.password.name }}" id="{{ form.password.id_for_label }}" class="form-control" style="width: 250px;" required>
      </div>
  
      <br/>

      <button type="submit" class="btn-lg btn-primary">Sign In</button>
      <p><a href="{% url 'password_reset' %}">Forgot your password? Reset it here.</a></p>
    </form>
  </center>
</div>

{% endblock %}

Codebase/events/templates/events/vendors.html
{% extends 'events/base.html' %}
<!DOCTYPE html>

{% block content %}

    <center class="HH2">
                
        <div class="center-container">
        
        <h2>Find Vendors</h2><br/>
    </center>
  
    <div class="center-container">
        <a href="{% url 'add_vendors' %}" class="btn-lg btn-primary mx-1">Add Vendor</a>
        <form method="get" action="{% url 'vendors' %}">
            <input class="dd_text" type="text" name="q" placeholder="Search...">
            <select class="dd_test" name="search_field">
                <option value="c_name">Vendor Name</option>
                <option value="types_of_product">Types of Product</option>
                <option value="events">Servicing Events</option>
            </select>
            <button class="btn-lg btn-primary" type="submit">Search</button>
        </form>
    </div>
    <br/>
    
    {% for v in vendors %}
        <div class="card">
            <div class="card-header">
                {{ v.c_name }}
            </div>
            <div class="card-body">
                <h6 class="card-title"><b>Product(s): </b> {{ v.types_of_product }} </h6>
                <p class="card-text">
                    <ul>
                        <strong>Owner:</strong> {{ v.c_owner }} <br/>
                        <strong>Address:</strong> {{ v.v_address }} <br/>
                        <strong>Events:</strong>
                        {% for has_vendors in v.hasvendors_set.all %}
                            {{ has_vendors.event.e_name }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </ul>
                </p>
            </div>
        </div>
        <br/>
    {% endfor %}

  

{% endblock %}